### ISSUE TITLE
setTimeout causing the gallery to speed up when user leaves the tab.

### ISSUE THREAD

**Issue by NicholasLancey** [wethegit/wtc-gallery-component#16]
The setTimeout on the `onHasChanged` callback is causing the gallery to speed up to where it `should` be when a user navigates away from the tab. The solution is to add a check using the visibility api below. Flagging this as an issue for now as I don't have the time to put a fix in place. 

https://github.com/wethegit/wtc-gallery-component/blob/master/src/wtc-gallery-component.js#L487

https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

@marlonmarcello @andrewrubin @liamegan @ShaiaBak - just so you're aware ^

**Comment by andrewrubin** [comment]
Thanks @NicholasLancey 

I don't think this is an issue with the Gallery Component though. While `setTimeout` may be throttled when a tab isn't focused, it certainly still runs.

I did a test here, where the body's background color changes on every slide change: https://codepen.io/team/wtc/pen/19df1d072f205078dd0baf9679239476

You can see that after navigating away from the tab and coming back, the autoplay timeout is still running as though it were the whole time.

---
I'm almost certain that this issue is specific to a use case where there's some other animating element within the gallery, hooked up to do something `onChange` of a gallery slide, but that _also_ depends on `requestAnimationFrame` for its animation. Since `rAF` is not executed when a tab loses focus, the animated element will not be synced up with the slide changes, after leaving said tab.

**Comment by liamegan** [comment]
Sure but then that's still a gallery issue, right? We want the gallery code to exist in a state where it is very difficult to cause these sorts of issues with code that should simply just work. If we stop the setTimeout from happening within the gallery when the user navigates away from the tab, then we also stop the onChange from being called.

**Comment by liamegan** [comment]
So the workflow update for this would be as follows:

- When the timeout fires, we check for frame visibility within the function.
- If the page is invisible, then we record the parameters and save them to a temporary datastore
- Then we set a visibilityChange listener to listen for when the page comes back into focus
- When it does we fire off the original event

This is a basic deferral cycle.

**Comment by andrewrubin** [comment]
Sounds good @liamegan !

**Comment by liamegan** [comment]
When this is done we need to publish this as a minor version so that we don't break any existing implementations and we need to ensure that QA is done against both the new version (as implemented in a new site) and against existing implementations.
